# Setup
title: Jelech's Blog
description: Just a coder
url: https://jelech.github.io
avatar: /avatar.png
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
  - vendor

collections:
  daily:
    output: true
    permalink: /:collection/:path/

# Optimize Jekyl SEO Tag
twitter:
  username: jelech
  card: summary
logo: logo.png
social:
  name: jelech
  links:
    # - https://twitter.com/jelech
    - https://github.com/jelech
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: jelech
  url: https://github.com/jelech
  email: jelech@hotmail.com
